export const TAURI_PARITY_MODULES: Array<{ name: string; ready: boolean; note?: string }> = [
  { name: "Academics", ready: true, note: "Planner DnD, program browser, GPA sheets" },
  { name: "Calendar", ready: true, note: "Edit, OAuth, ICS, Apple Calendar feed handoff" },
  { name: "Career", ready: true, note: "Apply Tier A–C + company GH/WD/Lever/Oracle/iCIMS/Talemetry boards" },
  { name: "Documents", ready: true, note: "Watchdog folders, Quick Look, DnD, cascade delete" },
  { name: "Finance connections", ready: true, note: "Local credentials + manual sync settings" },
  { name: "Discovery", ready: true, note: "School profile + CDS" },
  { name: "Assistant", ready: true, note: "~55 tools — full on-device tool registry (keyword planner)" },
  { name: "Finance", ready: true, note: "Goals, stock/crypto holdings, reports, donut charts" },
  { name: "Profile", ready: true, note: "Portfolio projects CRUD, advisor prep, experiences" },
  { name: "Resume", ready: true, note: "Live builder, section DnD, Typst/PDF export" },
  { name: "Catalog", ready: true, note: "Ingest, sync pipeline, semantic search" },
  { name: "Transfer", ready: true, note: "ASSIST import, community JSON, proof docs" },
  { name: "LMS", ready: true, note: "College window + bridge inject + scan/find + Keychain login autofill" },
  { name: "Settings", ready: true, note: "11 sections incl. OAuth sync-all + LMS defaults + parity panel" },
  { name: "Overview hub", ready: true, note: "Week ahead, deadlines, quick launch, advisor prep" },
  { name: "MapKit geocode", ready: true, note: "Nominatim + deep links" },
  { name: "Calendar OAuth", ready: true, note: "PKCE + Keychain + pull sync-all + push local events (EventKit write substitute)" },
  { name: "Bundled on-device AI", ready: true, note: "embed-384.clm + parse-instruct.clm ship in the installer (DirectML / MLX)" },
];
