#!/usr/bin/env python3
"""Generate Cursor feature-boundary rules from College/Features/ + manifest.

Usage:
  python3 scripts/generate-cursor-feature-rules.py --write   # regenerate rules
  python3 scripts/generate-cursor-feature-rules.py --check   # CI: fail if stale

Outputs:
  .cursor/rules/feature-boundaries-master.mdc
  .cursor/rules/features/feature-<name>.mdc  (one per discovered feature)
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass, field
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
FEATURES_DIR = REPO_ROOT / "College" / "Features"
TESTS_FEATURES_DIR = REPO_ROOT / "CollegeTests" / "Features"
PACKAGES_DIR = REPO_ROOT / "Packages"
PERSISTENCE_DIR = REPO_ROOT / "College" / "Core" / "Data" / "Persistence"
REPOS_DIR = REPO_ROOT / "College" / "Core" / "Data" / "Repositories"
TOOLBAR_DIR = REPO_ROOT / "College" / "App" / "Toolbar"
MANIFEST_PATH = REPO_ROOT / "scripts" / "feature-touch-manifest.json"
RULES_DIR = REPO_ROOT / ".cursor" / "rules"
FEATURE_RULES_DIR = RULES_DIR / "features"
MASTER_RULE_PATH = RULES_DIR / "feature-boundaries-master.mdc"

GENERATED_BANNER = (
    "<!-- AUTO-GENERATED by scripts/generate-cursor-feature-rules.py — do not edit by hand. -->"
)


@dataclass
class FeatureTouch:
    name: str
    slug: str
    description: str
    primary_globs: list[str] = field(default_factory=list)
    test_globs: list[str] = field(default_factory=list)
    package_globs: list[str] = field(default_factory=list)
    persistence_paths: list[str] = field(default_factory=list)
    repository_globs: list[str] = field(default_factory=list)
    toolbar_paths: list[str] = field(default_factory=list)
    app_wiring_paths: list[str] = field(default_factory=list)
    bridge_paths: list[str] = field(default_factory=list)
    parent: str | None = None
    related_features: list[str] = field(default_factory=list)


def load_manifest() -> dict:
    if not MANIFEST_PATH.is_file():
        return {"features": {}, "shell_no_touch_unless_asked": []}
    with MANIFEST_PATH.open(encoding="utf-8") as handle:
        data = json.load(handle)
    return data


def rel(path: Path) -> str:
    return path.relative_to(REPO_ROOT).as_posix()


def discover_feature_names() -> list[str]:
    if not FEATURES_DIR.is_dir():
        return []
    return sorted(p.name for p in FEATURES_DIR.iterdir() if p.is_dir())


def auto_persistence_paths(feature_name: str) -> list[str]:
    paths: list[str] = []
    if not PERSISTENCE_DIR.is_dir():
        return paths
    direct = PERSISTENCE_DIR / f"CollegePersistence+{feature_name}.swift"
    if direct.is_file():
        paths.append(rel(direct))
    token = feature_name.lower()
    for file in sorted(PERSISTENCE_DIR.glob("CollegePersistence+*.swift")):
        stem = file.stem.removeprefix("CollegePersistence+").lower()
        if stem.startswith(token) or token in stem:
            candidate = rel(file)
            if candidate not in paths:
                paths.append(candidate)
    return paths


def auto_repository_globs(feature_name: str) -> list[str]:
    if not REPOS_DIR.is_dir():
        return []
    token = feature_name.lower()
    seen: set[str] = set()
    ordered: list[str] = []
    for file in sorted(REPOS_DIR.glob("*.swift")):
        stem = file.stem.lower()
        if token in stem and "repository" in stem:
            base = file.name.split("+")[0]
            glob_path = rel(REPOS_DIR / f"{base}+*.swift") if "+" in file.name else rel(file)
            if glob_path not in seen:
                seen.add(glob_path)
                ordered.append(glob_path)
    return ordered


def auto_package_glob(feature_name: str, manifest_entry: dict) -> list[str]:
    if "package" in manifest_entry:
        return [manifest_entry["package"]]
    package_dir = PACKAGES_DIR / f"College{feature_name}"
    if package_dir.is_dir():
        return [f"Packages/College{feature_name}/**"]
    return []


def auto_toolbar(feature_name: str, manifest_entry: dict) -> list[str]:
    if "toolbar" in manifest_entry:
        return [manifest_entry["toolbar"]]
    candidate = TOOLBAR_DIR / f"{feature_name}ToolbarContent.swift"
    if candidate.is_file():
        return [rel(candidate)]
    return []


def auto_bridges(feature_name: str) -> list[str]:
    root = FEATURES_DIR / feature_name
    if not root.is_dir():
        return []
    return sorted(rel(p) for p in root.rglob("*Bridge.swift") if p.is_file())


def build_feature(name: str, manifest_features: dict) -> FeatureTouch:
    entry = manifest_features.get(name, {})
    description = entry.get("description", f"{name} feature UI and services.")
    slug = name.lower()

    touch = FeatureTouch(
        name=name,
        slug=slug,
        description=description,
        primary_globs=[f"College/Features/{name}/**"],
        parent=entry.get("parent"),
        related_features=list(entry.get("related_features", [])),
    )

    tests_dir = TESTS_FEATURES_DIR / name
    if tests_dir.is_dir():
        touch.test_globs.append(f"CollegeTests/Features/{name}/**")

    touch.package_globs = auto_package_glob(name, entry)
    touch.persistence_paths = list(entry.get("persistence", [])) or auto_persistence_paths(name)
    touch.repository_globs = list(entry.get("repositories", [])) if "repositories" in entry else auto_repository_globs(name)
    touch.toolbar_paths = auto_toolbar(name, entry)
    touch.app_wiring_paths = list(entry.get("app_wiring", []))
    touch.bridge_paths = auto_bridges(name)
    return touch


def all_globs_for_feature(touch: FeatureTouch) -> list[str]:
    globs = list(touch.primary_globs)
    globs.extend(touch.test_globs)
    globs.extend(touch.package_globs)
    return globs


def render_feature_rule(touch: FeatureTouch) -> str:
    globs = all_globs_for_feature(touch)
    glob_line = ",".join(globs)

    lines = [
        "---",
        f"description: \"{touch.name} feature — edit scope and boundaries\"",
        f"globs: {glob_line}",
        "alwaysApply: false",
        "---",
        "",
        GENERATED_BANNER,
        "",
        f"# {touch.name} feature scope",
        "",
        touch.description,
        "",
    ]

    if touch.parent:
        lines.extend(
            [
                f"**Parent area:** `{touch.parent}` — prefer keeping cross-cutting edits in the parent feature rule unless the task is Resume-only.",
                "",
            ]
        )

    lines.append("## Primary touch zones (edit freely)")
    for g in touch.primary_globs:
        lines.append(f"- `{g}`")
    if touch.package_globs:
        lines.append("")
        lines.append("## Extracted package")
        for g in touch.package_globs:
            lines.append(f"- `{g}`")
    if touch.test_globs:
        lines.append("")
        lines.append("## Tests")
        for g in touch.test_globs:
            lines.append(f"- `{g}`")

    shared_sections: list[tuple[str, list[str]]] = []
    if touch.persistence_paths:
        shared_sections.append(("Persistence (only when the task needs data writes)", touch.persistence_paths))
    if touch.repository_globs:
        shared_sections.append(("Repositories (only when the task needs data writes)", touch.repository_globs))
    if touch.toolbar_paths:
        shared_sections.append(("Toolbar (only when the task changes toolbar actions)", touch.toolbar_paths))
    if touch.app_wiring_paths:
        shared_sections.append(("App wiring (only when navigation/portal integration changes)", touch.app_wiring_paths))
    if touch.bridge_paths:
        shared_sections.append(("Bridges (cross-feature seams — change only when integration contract changes)", touch.bridge_paths))

    if shared_sections:
        lines.append("")
        lines.append("## Allowed shared touch")
        for title, paths in shared_sections:
            lines.append(f"### {title}")
            for path in paths:
                lines.append(f"- `{path}`")

    if touch.related_features:
        lines.append("")
        lines.append("## Related feature folders")
        for related in touch.related_features:
            lines.append(f"- `College/Features/{related}/**` (see `feature-{related.lower()}.mdc`)")

    lines.extend(
        [
            "",
            "## Do not touch without explicit user ask",
            "- Other `College/Features/*` folders",
            "- `College/App/ContentView.swift`, `SidebarView.swift`, `AppContainer.swift` (use ports/bridges)",
            "- Unrelated `College/Core/Data/Persistence/` or repository files",
            "",
            "## Cross-feature needs",
            "- Add or extend a port/protocol in `College/Core/` and wire it in `College/App/`",
            "- Never add `import College<OtherFeature>` across feature boundaries (see ADR 004)",
            "- After adding a new `College/Features/<Name>/` folder, run `python3 scripts/generate-cursor-feature-rules.py --write`",
            "",
        ]
    )
    return "\n".join(lines)


def render_master_rule(features: list[FeatureTouch], shell_paths: list[str]) -> str:
    lines = [
        "---",
        "description: Feature boundary map — where Cursor may edit for each product area",
        "alwaysApply: true",
        "---",
        "",
        GENERATED_BANNER,
        "",
        "# Feature boundaries (master plan)",
        "",
        "When implementing a feature or bug fix, **stay inside that feature's touch zones**.",
        "Open or @-mention the feature folder so the matching `feature-*.mdc` rule applies.",
        "",
        "## Layer model",
        "",
        "| Layer | Path | When to touch |",
        "| --- | --- | --- |",
        "| Feature UI + logic | `College/Features/<Name>/` | Default for all feature work |",
        "| Feature tests | `CollegeTests/Features/<Name>/` | Regressions for that tab |",
        "| Swift package | `Packages/College<Name>/` | Calendar, Academics, Career (compile-time boundary) |",
        "| Shared data | `College/Core/Data/Repositories/`, `CollegePersistence+<Domain>.swift` | Only when persistence contract changes |",
        "| Shell wiring | `College/App/` ports, toolbar, `AppContainer` | Only when navigation/toolbar/menu must change |",
        "| Cross-cutting | `College/Core/` (non-Data) | Design system, background services, security |",
        "",
        "## Feature index",
        "",
        "| Feature | Primary | Package | Tests | Rule file |",
        "| --- | --- | --- | --- | --- |",
    ]

    for touch in features:
        pkg = touch.package_globs[0].removesuffix("/**") if touch.package_globs else "—"
        tests = "✓" if touch.test_globs else "—"
        rule_file = f"features/feature-{touch.slug}.mdc"
        lines.append(
            f"| {touch.name} | `College/Features/{touch.name}/` | {pkg} | {tests} | `{rule_file}` |"
        )

    lines.extend(
        [
            "",
            "## Shell files — do not edit unless explicitly requested",
            "",
        ]
    )
    for path in shell_paths:
        lines.append(f"- `{path}`")

    lines.extend(
        [
            "",
            "## Adding a new feature",
            "",
            "1. Create `College/Features/<NewFeature>/` (and `CollegeTests/Features/<NewFeature>/` when tests exist).",
            "2. Add non-obvious persistence/repo/toolbar paths to `scripts/feature-touch-manifest.json` if needed.",
            "3. Run `python3 scripts/generate-cursor-feature-rules.py --write` — updates this master plan and `feature-<newfeature>.mdc`.",
            "4. CI runs `--check` so rules cannot drift.",
            "",
            "## Enforcement",
            "",
            "- `bash scripts/check-feature-imports.sh fail` — no cross-feature imports",
            "- `docs/adr/004-feature-module-boundaries.md` — package extraction plan",
            "- Per-feature rules in `.cursor/rules/features/` — scoped edit boundaries",
            "",
        ]
    )
    return "\n".join(lines)


def expected_outputs(features: list[FeatureTouch], shell_paths: list[str]) -> dict[Path, str]:
    outputs: dict[Path, str] = {
        MASTER_RULE_PATH: render_master_rule(features, shell_paths),
    }
    for touch in features:
        outputs[FEATURE_RULES_DIR / f"feature-{touch.slug}.mdc"] = render_feature_rule(touch)
    return outputs


def write_outputs(outputs: dict[Path, str]) -> None:
    FEATURE_RULES_DIR.mkdir(parents=True, exist_ok=True)
    # Remove stale generated feature rules
    if FEATURE_RULES_DIR.is_dir():
        for path in FEATURE_RULES_DIR.glob("feature-*.mdc"):
            if path not in outputs:
                path.unlink()
    for path, content in sorted(outputs.items()):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content if content.endswith("\n") else content + "\n", encoding="utf-8")


def check_outputs(outputs: dict[Path, str]) -> list[str]:
    errors: list[str] = []
    for path, expected in sorted(outputs.items()):
        if not path.is_file():
            errors.append(f"missing {path.relative_to(REPO_ROOT)}")
            continue
        actual = path.read_text(encoding="utf-8")
        if actual != (expected if expected.endswith("\n") else expected + "\n"):
            errors.append(f"stale {path.relative_to(REPO_ROOT)} (run generate-cursor-feature-rules.py --write)")
    if FEATURE_RULES_DIR.is_dir():
        for path in FEATURE_RULES_DIR.glob("feature-*.mdc"):
            if path not in outputs:
                errors.append(f"orphan {path.relative_to(REPO_ROOT)} (run --write)")
    return errors


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--write", action="store_true", help="Regenerate Cursor rules")
    group.add_argument("--check", action="store_true", help="Fail if generated rules are stale")
    args = parser.parse_args()

    manifest = load_manifest()
    manifest_features = manifest.get("features", {})
    shell_paths = list(manifest.get("shell_no_touch_unless_asked", []))

    names = discover_feature_names()
    if not names:
        print("generate-cursor-feature-rules: no features discovered", file=sys.stderr)
        return 1

    features = [build_feature(name, manifest_features) for name in names]
    outputs = expected_outputs(features, shell_paths)

    if args.write:
        write_outputs(outputs)
        print(f"generate-cursor-feature-rules: wrote {len(outputs)} file(s) for {len(features)} feature(s)")
        return 0

    errors = check_outputs(outputs)
    if errors:
        print("generate-cursor-feature-rules: stale or missing rules:", file=sys.stderr)
        for err in errors:
            print(f"  - {err}", file=sys.stderr)
        return 1

    print(f"generate-cursor-feature-rules: OK ({len(features)} features, {len(outputs)} files)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
